# Generated by Django 2.2.2 on 2019-07-17 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0005_auto_20190627_0309'),
        ('configuration', '0002_auto_20190627_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizConfigHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.IntegerField()),
                ('practice', models.BooleanField(default=False)),
                ('theory', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField()),
                ('origin_id', models.IntegerField()),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QuizConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice', models.BooleanField(default=False)),
                ('theory', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subject.Subject')),
            ],
            options={
                'ordering': ['id', 'subject'],
            },
        ),
    ]
