# Generated by Django 2.2.2 on 2019-07-24 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjectContent', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['id', 'answer']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['id', 'question']},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['id', 'subtopic']},
        ),
    ]
