# Generated by Django 2.2.2 on 2019-07-26 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjectContent', '0002_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
