# Generated by Django 2.2.2 on 2019-07-26 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
        ('subjectContent', '0003_delete_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.Subtopic')),
            ],
        ),
    ]
