# Generated by Django 2.2.2 on 2019-07-26 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjectContent', '0004_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subjectContent.Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subjectContent.Test'),
        ),
        migrations.AlterField(
            model_name='test',
            name='subtopic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subject.Subtopic'),
        ),
        migrations.AlterField(
            model_name='video',
            name='subtopic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subject.Subtopic'),
        ),
    ]
