# Generated by Django 2.2.2 on 2019-07-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjectContent', '0006_auto_20190728_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('subtopic_id', models.IntegerField()),
                ('created_date', models.DateTimeField()),
                ('origin_id', models.IntegerField()),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
