# Generated by Django 2.2.2 on 2019-07-25 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0001_initial'),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupstudent',
            unique_together={('student', 'group')},
        ),
    ]
