# Generated by Django 2.2.2 on 2019-07-24 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_auto_20190627_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupstudent',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group', to='group.Group'),
        ),
    ]
