# Generated by Django 2.2.2 on 2019-07-16 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0005_auto_20190627_1846'),
        ('userInfo', '0003_student_status'),
        ('subject', '0005_auto_20190627_0309'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.Group')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('att', models.BooleanField()),
                ('rating', models.FloatField()),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentProgress.GroupAttendance')),
                ('group_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.GroupStudent')),
            ],
        ),
        migrations.CreateModel(
            name='RealTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('score', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userInfo.Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='QuizRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('theory', models.IntegerField()),
                ('practice', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userInfo.Student')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.Topic')),
            ],
        ),
    ]
