# Generated by Django 2.2.2 on 2019-07-16 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentProgress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizrating',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userInfo.Student'),
        ),
        migrations.AlterField(
            model_name='quizrating',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subject.Topic'),
        ),
        migrations.AlterField(
            model_name='realtest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userInfo.Student'),
        ),
        migrations.AlterField(
            model_name='realtest',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subject.Subject'),
        ),
    ]
