# Generated by Django 2.2.2 on 2019-06-13 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentProgress', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestResult',
        ),
    ]
