# Generated by Django 2.2.2 on 2019-07-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentProgress', '0002_auto_20190716_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('theory', models.IntegerField()),
                ('practice', models.IntegerField()),
                ('topic_id', models.IntegerField()),
                ('student_id', models.IntegerField()),
                ('created_date', models.DateTimeField()),
                ('origin_id', models.IntegerField()),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='quizrating',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
