# Generated by Django 2.2.2 on 2019-07-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentProgress', '0003_auto_20190726_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupAttendanceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('group', models.IntegerField()),
                ('created_date', models.DateTimeField()),
                ('origin_id', models.IntegerField()),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAttendanceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('att', models.BooleanField()),
                ('rating', models.FloatField()),
                ('group_att', models.IntegerField()),
                ('group_student', models.IntegerField()),
                ('created_date', models.DateTimeField()),
                ('origin_id', models.IntegerField()),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='groupattendance',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
