# Generated by Django 2.2.2 on 2019-07-28 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentProgress', '0004_auto_20190728_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupattendancehistory',
            old_name='group',
            new_name='group_id',
        ),
    ]
