# Generated by Django 2.2.2 on 2019-07-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentProgress', '0004_auto_20190716_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizhistory',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
