# Generated by Django 2.2.2 on 2019-06-27 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_auto_20190627_1719'),
        ('userInfo', '0002_auto_20190627_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='configuration.UserStatusConfig'),
        ),
    ]
