# Generated by Django 2.2.2 on 2019-07-25 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
        ('subject', '0001_initial'),
        ('subjectContent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.Subtopic')),
            ],
        ),
        migrations.CreateModel(
            name='VideoAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access', models.BooleanField()),
                ('group_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.GroupStudent')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='access.Video')),
            ],
        ),
        migrations.CreateModel(
            name='TestAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access', models.BooleanField()),
                ('group_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.GroupStudent')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjectContent.Test')),
            ],
        ),
    ]
