# Generated by Django 2.2.2 on 2019-07-26 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoaccess',
            name='video',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
