# Generated by Django 2.2.2 on 2019-07-29 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_videoaccess_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testaccess',
            name='group_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='group.GroupStudent'),
        ),
        migrations.AlterField(
            model_name='testaccess',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subjectContent.Test'),
        ),
        migrations.AlterField(
            model_name='videoaccess',
            name='group_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='group.GroupStudent'),
        ),
        migrations.AlterField(
            model_name='videoaccess',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subjectContent.Video'),
        ),
    ]
